### ISSUE TITLE
Radiator miner option to define enabled devices on HiveOs

### ISSUE THREAD

**Issue by maximilienpaitel** [radifier/radiator#3]
Hi,

Thanks for the awesome Radiant miner ! 
I was trying to use this miner on a mixed Rig with AMD and Nvidia Gpus. 
Is there any option or will there be to enable only specific GPUs to use the miner ?

Thanks !

**Comment by radifier** [comment]
Use the -d argument to select which GPUs to use. See `ccminer --help` for more information.

**Comment by maximilienpaitel** [comment]
Thanks !

Indeed I can use -d or --devices (as it's based on ccminer, now I get it)
