### ISSUE TITLE
ccminer: malloc.c

### ISSUE THREAD

**Issue by AeroOne13** [radifier/radiator#5]
Hello, 
I have a problem with the miner, I have the following message. 
Any ideas ?

Rig : 2x1660s (6Go) + 1660 (6Go)
Hiveos : 5.10.0-hiveos #83
Nviadia Driver : N510.85.02

![2022-09-16_111945](https://user-images.githubusercontent.com/64043363/190610864-be2f7093-1f45-433b-a590-79980702d5c6.png)

**Comment by radifier** [comment]
Please try version 1.0.0 and let me know if this is resolved.

**Comment by AeroOne13** [comment]
Everything works perfectly, thank you
